CREATE TABLE IF NOT EXISTS menuRestaurant(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <>'')
);



CREATE TABLE IF NOT EXISTS restaurantTypes(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <>''),
  menuid integer REFERENCES menuRestaurant(id)
);


CREATE TABLE IF NOT EXISTS restaurants(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <>''),
  logo text NOT NULL,
  datePublished date NOT NULL,
  ownerName text NOT NULL,
  addressRestaurant text NOT NULL,
  restaurantType integer REFERENCES restaurantTypes(id),
  published BOOLEAN
);


INSERT INTO restaurantTypes(name)
  VALUES ('Comida rápida'),('Temáticos'),('Otros')

  INSERT INTO menuRestaurant(name, restaurantType)
  VALUES ('Hamburguesa' ,1 ),('Pizza', 1),('Pollo frito', 1),('Otros',1),
  		('Comida italiana' ,2 ),('Comida francesa', 2),('Otros',2),
		('Servicio a domicilio' ,3 ),('Restaurante gourmet', 3),('Otros',3)

INSERT INTO restaurants(name, logo, datePublished, ownerName, addressRestaurant, restaurantType, published)
  VALUES ('Kfc','logo.png','2021-07-04', 'KFC', 'Bulevar Morazan', 1, true),
  ('Mcdonals','logo2.png','2021-07-04', 'Ronal Mcdonal', 'Bulevar Juan Pablo II', 1, true),
  ('BurggerKing','logo3.png','2021-07-04', 'Burger', 'Bulevar Morazan', 1, true)
